# .circleci/config.yml
version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 12.5.1
    environment:
      FL_OUTPUT_DIRS: output
    steps:
      - checkout
      
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 11
            SCAN_SCHEME: Decafit

      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

workflows:
  build-and-test:
    jobs:
      - build-and-test
