# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Decafit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Decafit
	pod 'SwiftLint'
  pod 'SVProgressHUD'
  pod 'KeychainSwift', '~> 20.0'

  target 'DecafitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DecafitUITests' do
    # Pods for testing
  end

end
