# main.yml
name: CI-Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@master
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install
    - name: Build
      run: xcodebuild -workspace Decafit/Decafit.xcworkspace -scheme Decafit -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
    - name: Test
      run: xcodebuild -workspace Decafit/Decafit.xcworkspace -scheme Decafit -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' test
         
